/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_bagrorg_JniMatrixOperations */

#ifndef _Included_com_example_bagrorg_JniMatrixOperations
#define _Included_com_example_bagrorg_JniMatrixOperations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_bagrorg_JniMatrixOperations
 * Method:    add
 * Signature: ([I[I[I)V
 */
JNIEXPORT void JNICALL Java_com_example_bagrorg_JniMatrixOperations_add
  (JNIEnv *, jobject, jintArray, jintArray, jintArray);

/*
 * Class:     com_example_bagrorg_JniMatrixOperations
 * Method:    sum
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_com_example_bagrorg_JniMatrixOperations_sum
  (JNIEnv *, jobject, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
